name: iOS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test iOS
    runs-on: macos-latest

    env:
      SCHEME: 'iosApp'
      XC_WORKSPACE: 'composeApp/iosApp/iosApp.xcworkspace'
      IOS_DEVICE: 'iPhone 15'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant executable permission to gradlew
        run: chmod +x gradlew

      - name: Build shared framework
        run: ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
        env:
          SDK_NAME: iphonesimulator
          ARCHS: arm64

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer

      - name: Build and Test with Xcode
        run: |
          set -o pipefail
          xcodebuild test \
            -workspace "${{ env.XC_WORKSPACE }}" \
            -scheme "${{ env.SCHEME }}" \
            -destination "platform=iOS Simulator,name=${{ env.IOS_DEVICE }}" \
            | xcpretty