name: iOS Build

on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build iOS (Simulator)
        run: ./gradlew :composeApp:linkIosSimulatorArm64

      - name: Run iOS tests (optional)
        run: ./gradlew :composeApp:iosSimulatorArm64Test
